name: Task Issue
description: Use this template to create a new task issue.
title: "[Task] - Title"
labels: [task]

body:
  - type: input
    attributes:
      label: Task Title
      description: Enter the title of the task.
      placeholder: Task Title

  - type: input
    attributes:
      label: Due Date
      description: Enter the due date (YYYY-MM-DD).
      placeholder: YYYY-MM-DD

  - type: textarea
    attributes:
      label: Solution Description
      description: Describe how you plan to solve this issue.
      placeholder: Solution description here...

  - type: dropdown
    attributes:
      label: Phase
      description: Select the current phase of the task.
      options:
        - Planning
        - Development
        - Testing
        - Review
        - Complete

  - type: dropdown
    attributes:
      label: Priority
      description: Choose the priority level.
      options:
        - High
        - Medium
        - Low

  - type: dropdown
    attributes:
      label: Status
      description: Indicate the current status.
      options:
        - To Do
        - In Progress
        - Done
